### ISSUE TITLE
Upgrade to 2.8x required (Using Blender 2.8)

### ISSUE THREAD

**Issue by rico345100** [godotengine/godot-blender-exporter#287] opened 2019-11-06 14:34 UTC
**OS:**

Windows 10

**Godot version:**

Godot 3.1.1

**Blender version:**

Blender 2.8

**Issue description:**

After imported add-on it doesn't work with this message: "upgrade to 2.x required". I'm using 2.8.

**Minimal reproduction project:**

Download Blender 2.8 from official website, open it, import this add-on.

**Comment by corbac** [comment] 2019-11-06 15:34
not sure but I think it's because of the master branch is on the last blender version => 2.81 currently.
you have a branch for Blender 2.8 (2.80)

**Comment by rico345100** [comment] 2019-11-09 02:25
So means that I have to download at least 2.81? Was there any official release of 2.81? Because I don't want to use experimental build.

**Comment by corbac** [comment] 2019-11-22 10:30
Sorry @rico345100  I think I was wrong.
So just 
(1) Download official 2.8 release 
(2) clone or download the last master code or 2.8 branch (if the first doesn't work try second branch)
(3) Copy the "io_scene_godot" directory into Blender addons dir (do it manually, don't use blender UI)
(4) Run blender and look for the plugin on blender / Preferences

**Comment by akien-mga** [comment] 2019-11-22 11:33
I can't reproduce the issue, the current master branch (which you get with the "Download ZIP" button) works fine on Blender 2.80.

**Comment by Calinou** [comment] 2019-12-13 21:49
I'll close this as the add-on should now work on Blender 2.80. Blender 2.81 support is already being tracked in #295.

**Closed by Calinou** 2019-12-13 21:49 UTC
