### ISSUE TITLE
Blendshapes no longer work with Godot 3.2

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot-blender-exporter#207] opened 2019-04-21 12:03 UTC
**OS:**
Manjaro Linux 18.3

**Godot version:**
`master` / 7be498499

**Blender version:**
2.8-beta / 5ac7675f4

**Issue description:**
Blender shapes used to work with Godot 3.2 / Blender 2.8 before, but it stopped working recently. Sorry I cannot be more specific, since I'm constantly updating my Godot and Blender installations so it's not easy to determine the precise point when the bug was introduced.

At least, I managed to create a minimal Blender project to reproduce the issue. It contains a single cube with a single shape key.

And when I export it using the exporter, the resulting mesh in the `.escn` scene shows correct blend shape slider but changing it doesn't produce any visual effect.

On the other hand, if I open the scene in Blender 2.7 and export it using Better Collada, it produces a scene with corretly working blendshape.

**Minimal reproduction project:**

[blendshape.tar.gz](https://github.com/godotengine/godot-blender-exporter/files/3101169/blendshape.tar.gz)

**Comment by Jason0214** [comment] 2019-04-23 06:42
after some testing, it looks like a python API breakage in a recent blender2.8 beta build.

**Comment by Jason0214** [comment] 2019-04-28 23:50
I have tried hard to find where exactly the issue is, but failed..  I end up opening an topic at https://devtalk.blender.org/t/blender-2-8-shape-key-related-api-changed-recently/6904, hope I can get some help there

**Comment by Jason0214** [comment] 2019-05-17 09:12
fixed by #213

**Closed by Jason0214** 2019-05-17 09:12 UTC
Labels: bug
