### ISSUE TITLE
Still keyframes at start of animation

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot-blender-exporter#138] opened 2019-01-17 13:59 UTC
**OS:**

Linux.

**Godot version:**

3.0.6.stable.custom_build

Exporter: 66f3d73, plus the [blender 2.9 API patch](https://github.com/godotengine/godot-blender-exporter/pull/132).

**Blender version:**

Blender 2.79 (sub 6)
	build date: 2018-12-25
	build time: 20:34:04
	build commit date: 2018-12-22
	build commit time: 14:10
	build hash: 2c0c1f494dcf
	build platform: Linux
	build type: Release
	build c flags:  -Wall -Wcast-align -Werror=implicit-function-declaration -Werror=return-type -Werror=vla -Wstrict-prototypes -Wmissing-prototypes -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wlogical-op -Wundef -Winit-self -Wnonnull -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Wformat-signedness -Wrestrict -Wuninitialized -Wredundant-decls -Wshadow -Wno-error=unused-but-set-variable -Wimplicit-fallthrough=5 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fuse-ld=gold -fopenmp -std=gnu99   -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -msse2
	build c++ flags:  -Wredundant-decls -Wall -Wno-invalid-offsetof -Wno-sign-compare -Wlogical-op -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Werror=return-type -Werror=implicit-function-declaration -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wundef -Wformat-signedness -Wrestrict -Wuninitialized -Wundef -Wmissing-declarations -Wimplicit-fallthrough=5 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fuse-ld=gold -fopenmp -std=c++11   -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -msse2
	build link flags:  -Wl,--version-script='/build/blender/src/blender-2.79.b.git4.2c0c1f49/source/creator/blender.map'
	build system: CMake

**Issue description:**

My animation in blender looks smooth, but in godot there is a pause, caused by the first two frames being still.

This seems exactly like #114, but I can confirm I already have the patch for that (even took a look at the code to verify).

**Minimal reproduction project:**

[example.zip](https://github.com/godotengine/godot-blender-exporter/files/2768932/example.zip)
![out](https://user-images.githubusercontent.com/2496231/51323362-fd7e1c00-1a35-11e9-9dd2-a07050fe2e61.gif)

**Comment by Jason0214** [comment] 2019-01-18 05:47
I tested with your uploaded scene, I can confirm there is some bug in the exported animation length. However, after I adjusted the length, I am not able to reproduce the error on my Godot 3.0.6 stable.

![godot](https://user-images.githubusercontent.com/19422835/51367490-b88ecf80-1a9f-11e9-916a-4749e1b0e3bd.gif)
![blender](https://user-images.githubusercontent.com/19422835/51367486-b75da280-1a9f-11e9-9eb9-0e7b41de50a4.gif)

the first two frames:
![godot](https://user-images.githubusercontent.com/19422835/51367849-5cc54600-1aa1-11e9-877f-a91e4dd663c0.gif)
![blender](https://user-images.githubusercontent.com/19422835/51367851-5f27a000-1aa1-11e9-99d7-3bf164cb0193.gif)

kind of no idea what happened on yours..  could you give another try?

**Comment by Jason0214** [comment] 2019-01-18 05:52
One thing you may notice is that the angle of character's angle is different between godot and blender,  it is caused by the two 'foot' bone configured as not inherit parent rotation.
<img width="397" alt="screen shot 2019-01-17 at 21 49 42" src="https://user-images.githubusercontent.com/19422835/51367965-ee34b800-1aa1-11e9-9c15-9c1638d8067b.png">

Godot skeleton always inherit parent rotation and the exporter lack a convert for it, so it cause the inconsistency.

**Comment by rcorre** [comment] 2019-01-18 11:31
> after I adjusted the length

Can you clarify how you adjusted the length? I tried scaling down the animation in the Action Editor in blender and exporting again, but I've got the same issue. 

Thanks for the tip about the foot bone, I had noticed some weird rotation there. I got the idea from https://youtu.be/jp_SqjB0468?t=895, which suggests decoupling the foot rotation from the leg so you can control it entirely with the leg IK bone. Too bad that isn't supported in Godot.

**Comment by Jason0214** [comment] 2019-01-18 17:17
>Can you clarify how you adjusted the length? I
I mean the length at Godot side, I found the exporter has issue on it. 
<img width="692" alt="screen shot 2019-01-18 at 09 15 26" src="https://user-images.githubusercontent.com/19422835/51402201-ac3b5e80-1b01-11e9-8072-006fe031aabe.png">
in your uploaded scene,  0.5 is the correct value. 

Could you please upload your exported ESCN file here?  Maybe I can find something in it

**Comment by Jason0214** [comment] 2019-01-18 17:18
>which suggests decoupling the foot rotation from the leg so you can control it entirely with the leg IK bone. Too bad that isn't supported in Godot.

I see, really it is very useful. I created #140 , hope I can support it on the exporter side

**Comment by rcorre** [comment] 2019-01-19 13:38
> Could you upload your exported ESCN file here?

Here's a more minimal example (a very simple "leg" with an upper and lower leg bone, a foot IK, and a knee pull target). The zip has the escn and blender file. It is a 15 frame animation (0 to 14) at 30fps -- it should be exactly 0.5s in length. However, in godot it is 0.4s.

I'm reasonably sure my code in #132 was wrong, I think I need to pass `frames=range(start_frame, end_frame+1)`. However, even with that the animation is still too short. I see you just merged #141, might that be related?

**Comment by rcorre** [comment] 2019-01-19 17:09
> I see you just merged #141, might that be related?

Doesn't seem like it helped. The exported animation is still 0.4s with that patch. If I use `frames=range(start_frame, end_frame+1)`, it is 0.43.

Frame 0 has the knee straight in blender but slightly bent in godot, so it seems like I'm actually missing frames from the _start_ of the animation.

![1547917650](https://user-images.githubusercontent.com/2496231/51430014-d87adc00-1be2-11e9-8141-253a16330d2c.png)

I forgot to attach the example before, here it is:
[example2.zip](https://github.com/godotengine/godot-blender-exporter/files/2775767/example2.zip)

The .escn in that zip is the export _with_ the `end_frame+1` patch.

**Comment by Jason0214** [comment] 2019-01-19 17:36
>Frame 0 has the knee straight in blender but slightly bent in godot, so it seems like I'm actually missing frames from the start of the animation.

I checked your .blend file,  the action has the first keyframe 0, while the `scene.frame_start` is set as 1, that's the reason the first frame is missing.
<img width="482" alt="screen shot 2019-01-19 at 09 23 02" src="https://user-images.githubusercontent.com/19422835/51430166-da857080-1bcb-11e9-9e0e-d2d24f28a8cd.png">

because when you play a action in blender, it actually plays in the range of [scene.frame_start, scene.frame_end] ( in your case [1, 13] ).  To have this consistency, the exporter is designed to shift action keyframes to put the `scene.frame_start` as the frame 0 in godot.  (This part have not added to the doc, I may need to do it right now 😅)

if you do a little check, you can find the frame 0 in godot is actually the frame 1 which is the `scene.frame_start` in blender.

---

>The exported animation is still 0.4s with that patch. If I use frames=range(start_frame, end_frame+1), it is 0.43.

I tested your scene with HEAD of the master branch,  it gives length 0.43,  equals to (14 -1) / 30, I think it is correct

---
by the way #141 is not related to your issue.

**Comment by rcorre** [comment] 2019-01-19 19:08
Aha! Yes, fixing the start frame fixes my second example. That's good to know, I didn't know the exporter considered that.

However, my original example is still frozen at the start of the animation unless I use `frames=range(start_frame, end_frame+1)`. I'm reasonably sure that we want to bake frames [0, 14] rather than [0, 14), but I'll investigate a bit more.

**Comment by Jason0214** [comment] 2019-01-19 19:42
Really appreciate your work.  You might be right, as far as I can remember, I didn't think much when I wrote baking action in range `start_frame, end_frame`, I will also do some test example to figure it clear.

**Comment by Jason0214** [comment] 2019-01-19 22:34
You are welcome :)    Then I will close this thread for now, feel free to open issue if you any questions. Cheers!

**Closed** 2019-01-20 16:53 UTC
Labels: bug
