### ISSUE TITLE
Emissions property issues and export options not given

### ISSUE THREAD

**Issue by Raj2032** [godotengine/godot-blender-exporter#153] opened 2019-02-04 23:51 UTC
I exported an object that contains ICO sphere with emssions property and the color of it was yellow. When exported first of all for some reason I did not get these options at all, however I got it for my other objects.
![1](https://user-images.githubusercontent.com/29293830/52244646-b7302480-2932-11e9-9cc3-d48ad33876e7.PNG)

Second of all when exported, the origin point did was set to the bottom of the object rather than the top.
![image](https://user-images.githubusercontent.com/29293830/52244743-0fffbd00-2933-11e9-8cd7-4fe711c31ba4.png)

![image](https://user-images.githubusercontent.com/29293830/52244788-34f43000-2933-11e9-943c-70da4f593eef.png)

This is how it looks like in rendered view in Blender.

![image](https://user-images.githubusercontent.com/29293830/52244812-56edb280-2933-11e9-8bca-380e8e4735fd.png)
This is what it looks like on Godot. The eyes are not fully yellow for some weird reason. All though the emissions material does not work at all.

Note that I  parented another object to this object in Blender.

**Comment by Jason0214** [comment] 2019-02-09 06:41
Sorry for the late reply.

The offset of the origin point might be caused the parent object, I suppose you are exporting only that object without it parent right? 

>The eyes are not fully yellow for some weird reason. All though the emissions material does not work at all.
I would do some test to the emission material when I have time

**Comment by Raj2032** [comment] 2019-02-09 07:14
@Jason0214 All good :)



> The offset of the origin point might be caused the parent object, I suppose you are exporting only that object without it parent right?

I exported the parented object as well.

> I would do some test to the emission material when I have time

Thanks for your help :)

Also I want to point out after when I posted this post. I had another issue when exporting the main object with the parented object. In blender deleted the parented object and I created a new object and parented to the main object. When I export the entire model for some reason it does not export the new parented object but the old parented object and in a weird size.

**Comment by Jason0214** [comment] 2019-02-09 07:24
Hi Raj,  I read your description and don't have much idea about what could be happened (there are some test cases ensuring the simple parenting relation exporting would work).  If you are willing, could you give a try to export again clean the .import/ folder and foo.import file,  sometimes when an opened escn scene was written to, the whole scene would broken, and only clear all the caches could fix it. Thanks.

**Comment by Raj2032** [comment] 2019-02-09 07:24
@Jason0214 Sure I will give it a try thanks.

**Comment by Raj2032** [comment] 2019-02-09 07:27
Is foo.import file located inside .import/ folder?

**Comment by Jason0214** [comment] 2019-02-09 07:30
there is a .import file in the same directory as the .escn file,  and there is another a cached object (name ends with some hash value) in .import folder, for this one you can just remove the whole .import folder, it won't hurt

**Comment by Raj2032** [comment] 2019-02-09 07:36
So I re-exported the object, deleted everything inside the .import folder, and when I opened up Godot and opened up the project, surprisingly the parented object now exported correctly to Godot. But there is another issue, the object has some strange lines drawn to the object.

This is what it looks like in Blender in rendered view (note that I am also pointing a sun directly at the gold parented object)
![image](https://user-images.githubusercontent.com/29293830/52518105-86851d80-2c99-11e9-971d-b8a8dc9e21ff.png)

This is what it looks like in Godot, see these weird lines on the golden object?
![image](https://user-images.githubusercontent.com/29293830/52518109-969cfd00-2c99-11e9-9dc2-dda965647933.png)

**Comment by Jason0214** [comment] 2019-02-09 07:50
Next time when you exporting blender scene to some escn, make sure the escn file is not opened in godot, otherwise, some cache would broken in some godot version and generate weird scene.

>these weird lines on the golden object?
looks like in the mesh in blender normal is smooth and in godot its flat, but not sure, can I ask what material are you using for this yellow mesh?

> for some reason I don't get those objects such as if I want to export the sun (for example)
There are some objects could not be exported.  Objects can be exported are lamp, armature, mesh, camera, if some object in this category are not exported, it could be an issue. By the way, just have a check on the exporting options, there are several options also controls which objects get exported.

Sorry, I may need to look at the above issues tomorrow, bed time now 😄

**Comment by Raj2032** [comment] 2019-02-09 08:52
@Jason0214 >Next time when you exporting blender scene to some escn, make sure the escn file is not opened in godot, otherwise, some cache would broken in some godot version and generate weird scene.

Sure I will keep that in mind.

In Blender it was set to "flat" Are you talking about this setting?
![image](https://user-images.githubusercontent.com/29293830/52518714-22675700-2ca3-11e9-8ac5-809cf531f3c1.png)

This is also strange, when I set it to "smooth" in Blender, then I see those strange lines

(Rendered view)
![image](https://user-images.githubusercontent.com/29293830/52518760-f26c8380-2ca3-11e9-804b-e2a5b8c633bb.png)

>There are some objects could not be exported. Objects can be exported are lamp, armature, mesh, camera, if some object in this category are not exported, it could be an issue. By the way, just have a check on the exporting options, there are several options also controls which objects get exported.

Sorry I poorly phrased that, I ment to say that I don't see any options like these
![image](https://user-images.githubusercontent.com/29293830/52518769-22b42200-2ca4-11e9-9afe-0a4b6d9427a9.png)
when exporting this particular object.

> Sorry, I may need to look at the above issues tomorrow, bed time now 😄
Good night =D

**Comment by Jason0214** [comment] 2019-02-10 06:56
> In Blender it was set to "flat" Are you talking about this setting?

Yes it is what I am talking about.  This lines actually is the non-continuous normal at the connection of two face, so it is part of the vertex data, so it is not strange that you can see them in `Solid` view. Actually you'd better refer to `Solid` view when you change this 'shading mode'. If you want to export a smooth shading mesh, just play with this button and make your mesh looks smooth in blender `Solid` view and then export it.

> Sorry I poorly phrased that, I ment to say that I don't see any options like these

Ah, sorry, I just noticed you have mentioned it in the first message.  Hmm, it is kind of strange,  can I ask what version of blender are you using? also just to confirm, are you call exporter through the menu bar?  as there are other ways to call the exporter.
<img width="545" alt="screen shot 2019-02-09 at 22 53 19" src="https://user-images.githubusercontent.com/19422835/52530690-dd9ce980-2cbd-11e9-8930-a7e5f76dc38c.png">

**Comment by Raj2032** [comment] 2019-02-10 13:34
@Jason0214 
> If you want to export a smooth shading mesh, just play with this button and make your mesh looks smooth in blender `Solid` view and then export it.

I absolutely don't want to export the object using the smooth shader, I am exporting the obect with the flat shader and even then I am still getting those weird lines.

> can I ask what version of blender are you using?
I am using 2.79.

> also just to confirm, are you call exporter through the menu bar?
Yes that is absolutely what I am doing.

**Comment by Jason0214** [comment] 2019-02-10 19:21
The `smooth` shading would be the one without 'those lines'. according to your description, I don't have much idea why you are getting the opposite effect, maybe it is necessary to check Blender manual to see if there are other options controls it.

The missing of exporter option Panel is also strange, more likely it's about the configuration of your blender not the exporter ( I can confirm the panel shows up on blender2.79a 2.79b on OSX, Windows and Ubuntu Linux with default settings).Try to search something like 'hide/show blender operator panel', there might be some blender options for it.  Feel sorry I am not able to give you more help

**Comment by Raj2032** [comment] 2019-02-10 22:58
@Jason0214 
> The `smooth` shading would be the one without 'those lines'. according to your description, I don't have much idea why you are getting the opposite effect, maybe it is necessary to check Blender manual to see if there are other options controls it.

I will check it out

> The missing of exporter option Panel is also strange, more likely it's about the configuration of your blender not the exporter ( I can confirm the panel shows up on blender2.79a 2.79b on OSX, Windows and Ubuntu Linux with default settings).Try to search something like 'hide/show blender operator panel', there might be some blender options for it. Feel sorry I am not able to give you more help

Not too sure as with other models these options do appear, just with this model it does not appear these options when exporting so not too sure.

> Try to search something like 'hide/show blender operator panel'

Yeah sure I will check it out.

> Feel sorry I am not able to give you more help

Its all good thanks for your help :)

**Comment by Jason0214** [comment] 2019-02-11 17:55
> just with this model it does not appear these options when exporting so not too sure.

so strange.., it is not very likely the model would affect the addon's registering.

I will close this issue for now, feel free to reopen/open up new if you have further questions. 
Cheers! :tada:

**Comment by Raj2032** [comment] 2019-02-12 00:40
Thanks :)

But have a question about emissions is it possible if it can be supported?

**Comment by Jason0214** [comment] 2019-02-12 00:43
Ah sorry, totally forget the emission issue...  I will have a check on it

**Comment by Raj2032** [comment] 2019-02-12 00:45
Thanks :)

**Comment by Jason0214** [comment] 2019-02-17 05:20
I compared the emission between Blender EEVEE (which is also based on rasterization) and output from the exporter.
<img width="759" alt="screen shot 2019-02-16 at 16 33 26" src="https://user-images.githubusercontent.com/19422835/52908701-bbf8b080-322f-11e9-8d0c-e44b479e0bfb.png">
<img width="810" alt="screen shot 2019-02-16 at 16 37 39" src="https://user-images.githubusercontent.com/19422835/52908703-bd29dd80-322f-11e9-98e6-3080f0b5b939.png">
looks like the color of emission works fine.

But I have to say in your given screenshots, that color looks weird, might be some issue other than emission. If you can give more information about the material used (such as what is the shader node tree looks like), it could be helpful to find out the issue.

---
Besides, it is normal that the emission effect would be very limited compared with blender `render` which is based on path tracing.

**Comment by Raj2032** [comment] 2019-03-14 22:44
@Jason0214 Sorry for some reason I was not aware that you sent me a message on this post.

So with your exported model that has an emissions model, in Godot does the other objects relfect light from this emissions model?

**Comment by Jason0214** [comment] 2019-03-17 05:20
As always I am not very confident about my knowledge in rendering, so what I am saying might be wrong

According to https://docs.godotengine.org/en/3.0/tutorials/3d/spatial_material.html?highlight=spatial#emission  `Emission` only emit lights when GI probe is used, so if you directly use the escn generated by this exporter, the emission would be no affect unless you setup some GI.

Also even if you set up GI, I think you should not expect it has the same effect as blender cycle engine. Global illumination (arbitrary shape light, reflection between objects) is very expensive in rasterization.

**Comment by Jason0214** [comment] 2019-03-24 18:10
close as main issue are solved, feel free to reopen or open new one is you still has questions

**Closed by Jason0214** 2019-03-24 18:10 UTC
Labels: bug

**Comment by Raj2032** [comment] 2019-03-25 07:21
I see thanks
