### ISSUE TITLE
simple hierarchies with wireframe physic and animation not exported correctly

### ISSUE THREAD

**Issue by Olm-e** [godotengine/godot-blender-exporter#98] opened 2018-10-10 10:47 UTC
hello,
I'm trying to export a simple hierarchy of objects with simple animation and the result in godot is not conserving all needed.
it consist of wireframe meshes used as physic collision to which visible mesh are parented, with simple animation (rotation) on one child physic mesh
hierarchy like this : 

BaseCollisionMesh (set to wireframe)(active rigidbody)
-BaseMesh
-ArmCollisionMesh (animated) (set to wireframe)(active rigidbody)
--ArmMesh

result in godot exported with SCENE_ANIMATION is giving

BaseCollisionMesh (rigidbody)
-BaseCollision (collisionshape)
-BaseMesh (mesh)
-ArmCollisionMesh (collisionshape)
-ArmMesh (mesh) (location reset to 0.0.0)

and no animation

if the collision meshes are set to normal render, the animation is exported, a "better" hierarchy too, but still no rigidbody and correct parenting ... 

here is the simple test I made to play with : 
[blender-export-phystest.zip](https://github.com/godotengine/godot-blender-exporter/files/2464317/blender-export-phystest.zip)

**Comment by Jason0214** [comment] 2018-10-14 06:44
Thank you for report this issue, I can confirm it is a bug and it caused by currently we simply bypass a wireframe mesh.  I think there may be workaround, you can create an additional empty node as the parent of Cube.003 in your scene, then apply the transform and animation to the empty node, instead of to the wireframe mesh.    Anyway I will create a PR to fix this issue later.

**Comment by Jason0214** [comment] 2018-11-06 06:29
closed via #100, 

>BaseCollisionMesh (set to wireframe)(active rigidbody)
-BaseMesh
-ArmCollisionMesh (animated) (set to wireframe)(active rigidbody)
--ArmMesh

This hierarchy should be work.

**Closed by Jason0214** 2018-11-06 06:29 UTC
Labels: bug
