### ISSUE TITLE
Support texture import

### ISSUE THREAD

**Issue by r-mice** [godotengine/godot-blender-exporter#72] opened 2018-08-09 12:39 UTC
In godot the model not has texture when importing from Blender, this can be make manually, but have an option to auto import the image texture would be great.

**Comment by sdfgeoff** [comment] 2018-08-09 12:46
Blender Internal materials will not be supported because they are removed from blender 2.8, but cycles materials will be supported. See PR #56, which should be merged fairly soon.

Closing as (almost a) duplicate of #35

**Closed by sdfgeoff** 2018-08-09 12:46 UTC
