### ISSUE TITLE
Different bone transform between Blender and Godot

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot-blender-exporter#145] opened 2019-01-21 23:16 UTC
**OS:**
Manjaro Linux 18.0.2

**Godot version:**
Master / `93d8f3cdd5`

**Blender version:**
2.8

**Issue description:**
When I export a character animation using the exporter, the character's head position looks different in Godot compared to how it was in the original design.

This is how it looks like in Blender (see where the eyesight is pointed at):
![blender](https://user-images.githubusercontent.com/2367032/51503172-f16ed180-1e1c-11e9-9b6d-b4c76a5f0fd1.png)

And this is how it looks like in Godot at roughly the same frame:
![godot](https://user-images.githubusercontent.com/2367032/51503175-f59aef00-1e1c-11e9-9574-8cb0f3ab9744.png)

It looks like one or more of the bones among `spine03`, `spine02`, `spine01`, `head` have wrong rotation value in certain frames. I tried to manually bake the action before exporting it, but it doesn't seem to have any effect in the result.

**Minimal reproduction project:**
Unfortunately, I don't have a minimal test case, but the problematic Blender files are available here:
* https://github.com/mysticfall/AlleyCat/commit/b7f489728b088a617e29ade597357221308f80c6

**Comment by mysticfall** [comment] 2019-01-22 05:45
Just to make the symptom clearer, if anyone would try the example I linked - it doesn't happen for every frame, so the head position looks ok at the beginning of the animation.

But the character stoops forward more than it's designed to do in a certain phase of a run cycle (the one shown in the screenshots), so that the character shows a bit of chicken like head / chest movements in Godot, if you compare the lateral offset of its head position compared to its root bone.

**Comment by Jason0214** [comment] 2019-01-28 00:42
I spend some time to look up the issue,  haven't find the root cause, but I will post some update here  for further investigation.

I think I can confirm the animation data is consistent between escn and blender, issue might be in the armature structure ( i.e. the rest matrix of bone )

I looked at two frames which obviously has that 'chicken like head' and checked the pose matrix of bone 'head'.  

---
One is `time=0.5` ( in blender `frame=12`)

the pose matrix in Godot ( pose is evaluated from animation data)
<img width="1066" alt="screen shot 2019-01-27 at 16 16 07" src="https://user-images.githubusercontent.com/19422835/51809038-f7b3e200-2250-11e9-8bff-a04ee8a1f4f4.png">

the pose matrix in blender (note that the first row is vector x, etc..)
<img width="694" alt="screen shot 2019-01-27 at 16 16 02" src="https://user-images.githubusercontent.com/19422835/51809058-2f228e80-2251-11e9-97fa-711895d937d9.png">

looks fine to me.

---
the other frame is `time=1.16` ( in blender `frame~=28` )
<img width="1136" alt="screen shot 2019-01-27 at 16 25 42" src="https://user-images.githubusercontent.com/19422835/51809079-89bbea80-2251-11e9-99c7-374d193a92bc.png">


<img width="707" alt="screen shot 2019-01-27 at 16 34 34" src="https://user-images.githubusercontent.com/19422835/51809075-76a91a80-2251-11e9-89ef-31f93013c53e.png">

also not much difference.

---

In godot,  for a bone in Skeleton `s`, with ancestors `p0, p1, p2, root`,  its transform is evaluated as `s.transform * root.rest * p2.rest * p1.rest * p0. rest * p0.pose`.    All the `rest` matrix is part of Skeleton node, they are not changed by any animation. So I guess there might be some issue in the long chain of rest matrix in this rig. I will keep investigate it

**Comment by Jason0214** [comment] 2019-02-11 18:08
Looks like it is fixed in the current HEAD

**Closed by Jason0214** 2019-02-11 18:08 UTC
Labels: blender2.8, bug
