### ISSUE TITLE
Support importing animations

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot-blender-exporter#38] opened 2018-06-03 23:55 UTC
* Version : `master` / 88a8803cd

Currently, it seems that the exporter does not import animations even when the relevant setting is enabled in the associated import settings.

Possibly it could be simply because the feature hasn't been implemented yet, but I'm reporting it to track progress.

**Comment by Jason0214** [comment] 2018-06-04 00:31
yes, the animation is not implemented in master yet, but it will be not long to have it

**Comment by mysticfall** [comment] 2018-06-04 00:35
Great news :) Thanks for letting me know!

**Comment by sdfgeoff** [comment] 2018-06-15 07:57
Will be resolved when #49 is merged (which should happen relatively soon)

**Comment by mysticfall** [comment] 2018-07-14 03:52
Finally had time for testing this but I found several problems.

When I tried to export [walking animations](https://github.com/mysticfall/AlleyCat/blob/master/Design/Blender/Characters/Human/Female/Animations%20-%20Locomotion.blend) contained in my project and opened the imported scene, the created animation player only contained tracks for a few bones so it didn't play correctly.

And also, it seems that currently it only exports the active animation while ignoring other defined animations in the same Blender file.

If you need more information, please let me know.

**Comment by sdfgeoff** [comment] 2018-07-16 07:35
@mysticfall 
Simple test files that isolate the problem are helpful in diagnosing the problem, but I had a short look this morning.

> And also, it seems that currently it only exports the active animation while ignoring other defined animations in the same Blender file.
Hmm. This is quite challenging. How does the exporter know which animations are linked to which objects? As far as I can tell, actions can be assigned to any object, and so the only one we "know" is linked to an object is the active one. I'm not very experienced with blender's animation systems, so it's possible I'm missing something. If I am, please let me know.

I'm also not sure how to handle the case you have in your project where you have two blend files with animations on the same object. Any suggestions?

>When I tried to export walking animations contained in my project and opened the imported scene, the created animation player only contained tracks for a few bones so it didn't play correctly.

Possibly non-deform/control bones containing animation data aren't being handled correctly? Or possibly it's to do with bone layers (I didn't even know there were bone layers). @Jason0214, do you want to look into this or should I?

**Comment by mysticfall** [comment] 2018-07-16 07:48
Oh yeah, it makes sense if the missing animation tracks was caused by bones being separated into different bone layers.

As to the problem of only the active action being exported, I also lack adequate knowledge of how Blender works internally, but there's an option(`use_anim_action_all`) to export all animations in Better Collada addon which I've been using to export all linked animations in my model:

* https://github.com/godotengine/collada-exporter/blob/master/io_scene_dae/export_dae.py#L1789

Hope this could help, in case you need a reference of such a feature.

**Comment by Jason0214** [comment] 2018-07-18 22:35
Sorry, I totally missed this thread,  (weird github didn't send me an email when I was being @ ).  
- I didn't realize bone animation would be separated by layers, I will fix it. 
- currently If you push your action down to nla stack, it can be exported. Seems Better Collada use bone names to match an action to a object, I will think about it if it can be supported in this addon. Thank you for testing and providing very useful information @mysticfall

**Comment by Jason0214** [comment] 2018-07-25 04:06
Seems bone layer does not separate animations.

After I take a look at the woman case, I found the following deformed bone only contribute the slight swing of head and shoulder
![image](https://user-images.githubusercontent.com/19422835/43178822-4a009360-8f84-11e8-83ba-c03dbc88d59e.png)
(I mute them and the animation mainly not changed
so I suppose the movement of arm and thigh is caused by IK?  which is not supported not

For export none active actions, do you think it's really needed @mysticfall ?  I don't know how you guys make use of nla_stacks, if you don't use it very much, then it is worthwhile to have a support for exporting `dangling actions` to make your working more smoothly.  (although implement it is a little hacky

**Comment by mysticfall** [comment] 2018-07-30 08:44
Sorry for the late response. Yes, you are right about the animation is largely consisted of IK bones. Somehow I forgot about it and failed to mention the fact. Should I file for a separate feature request for IK support then?

I used to bake the animation before exporting when the other Godot exporter didn't support IK. It was quite a cumbersome process, so I hope it could be supported in future.

As to the exporting of non active actions, I found that it's much easier to make a single Blender file to define multiple related animations (i.e. walking in various directions) and export them all at once since otherwise, I'd need to export each animations separately and manually add them to a `AnimationPlayer` one by one which would be quite a time consuming process.

I haven't used NLA stacks so I'm not sure if it could help the workflow in this case. If so, I'm willing to try it, if supporting dangling actions prove to be difficult.

**Comment by Jason0214** [comment] 2018-07-31 19:51
No need to have a separate issue, I am working on IK in #63, already tested it on your test case and it works good.

Current I made this addon able to export non-active action if you add them into nla_tracks. I found a lot of functionality of nla_tracks is not complete yet, but it works good for stashing action.  I can show you how to use it, if you are willing to have a try on it.

1. switch work space to nla editor
<img width="631" alt="wx20180731-114222 2x" src="https://user-images.githubusercontent.com/19422835/43483249-e667a3fc-94bf-11e8-8ef3-c5c5e0c8b19a.png">
2. You can find the active action of the current object (the bar in orange), and also all the actions already be stashed into this object. Then click the down arrow beside the active action, it would be stashed into nla_tracks
<img width="747" alt="wx20180731-114153 2x" src="https://user-images.githubusercontent.com/19422835/43483302-19f27012-94c0-11e8-8606-7aeb9778f354.png">
3. now you can see there is no active action on the object right now, the previous action already be stashed.
<img width="626" alt="wx20180731-114300 2x" src="https://user-images.githubusercontent.com/19422835/43483335-3ac9aa08-94c0-11e8-94be-96ddbc65fd79.png">
4. export the scene use blender exporter, you can find all the stashed action being exported.
<img width="953" alt="wx20180731-124413 2x" src="https://user-images.githubusercontent.com/19422835/43483364-5296e718-94c0-11e8-84c2-7fde40b9d98d.png">

**Comment by mysticfall** [comment] 2018-07-31 21:10
You guys never fail to amaze me with how fast you are working on those issues. I can't wait to try out #63  :)

And thanks much for the explanation about using NLA stacks. Yes, I don't mind changing my workflow as long as I can export all animations at once.

**Comment by Jason0214** [comment] 2018-08-01 00:50
I suppose the original functionality of NLA tracks is to play multiple action at once (so it would be non linear interpolated),  while blender document also suggested it can be used to stash action [https://docs.blender.org/manual/en/dev/editors/nla/tracks.html#action-stashing](https://docs.blender.org/manual/en/dev/editors/nla/tracks.html#action-stashing)

**Comment by guilhermefelipecgs** [comment] 2018-08-06 00:29
> Current I made this addon able to export non-active action if you add them into nla_tracks. I found a lot of functionality of nla_tracks is not complete yet, but it works good for stashing action. I can show you how to use it, if you are willing to have a try on it.

@Jason0214 Is this working? I can't export/import multiple animations yet. I tested with this pr #63.
![captura de tela de 2018-08-05 21-22-58](https://user-images.githubusercontent.com/1387165/43691660-28a77870-98f6-11e8-872c-58df40747c58.png)
Only "Anim2" is imported with name "Action".
![captura de tela de 2018-08-05 21-27-16](https://user-images.githubusercontent.com/1387165/43691674-5d0fa7fe-98f6-11e8-941e-4b58f7ab7d66.png)

Godot demo with blender file:
[Multiple Animarions.zip](https://github.com/godotengine/godot-blender-exporter/files/2260831/Multiple.Animarions.zip)

**Comment by Jason0214** [comment] 2018-08-06 01:51
@guilhermefelipecgs  seems my last modification of #63 broken nla_tracks, will be fix by #66

**Comment by Jason0214** [comment] 2018-08-08 18:07
Another issue raised, really apologize
`nla_tracks` should be well supported when #71 merges

**Comment by guilhermefelipecgs** [comment] 2018-08-08 18:12
Thanks for your good job with this exporter. I hope to migrate completely from Dae to escn.

**Comment by Jason0214** [comment] 2018-08-08 18:20
Thank you for your support. Really glad to hear that.  While there still a lot need to do in this addon,  hope we can finally simplify the workflow from Blender to Godot.

**Comment by Jason0214** [comment] 2018-10-23 05:30
Animation exporting seems to be stable now. There is one remaining issue about nla_tracks, it would be updated in #90,  so I will close this thread.

**Closed by Jason0214** 2018-10-23 05:30 UTC
Labels: enhancement
