### ISSUE TITLE
Runtime error when exporting mesh

### ISSUE THREAD

**Issue by Dogpot** [godotengine/godot-blender-exporter#217] opened 2019-05-25 21:30 UTC
**OS:**
Win10

**Godot version:**
Godot 3.1.1 x64 stable

**Blender version:**
blender-2.80.0-git.e1d1899e7290-windows64

**Issue description:**
Traceback (most recent call last):
  File "D:\Temp\blender-2.80.0-git.e1d1899e7290-windows64\2.80\scripts\addons\io_scene_godot\__init__.py", line 205, in execute
    return export_godot.save(self, context, **keywords)
  File "D:\Temp\blender-2.80.0-git.e1d1899e7290-windows64\2.80\scripts\addons\io_scene_godot\export_godot.py", line 292, in save
    exp.export()
  File "D:\Temp\blender-2.80.0-git.e1d1899e7290-windows64\2.80\scripts\addons\io_scene_godot\export_godot.py", line 249, in export
    self.export_scene()
  File "D:\Temp\blender-2.80.0-git.e1d1899e7290-windows64\2.80\scripts\addons\io_scene_godot\export_godot.py", line 205, in export_scene
    self.export_object(obj, root_gd_node)
  File "D:\Temp\blender-2.80.0-git.e1d1899e7290-windows64\2.80\scripts\addons\io_scene_godot\export_godot.py", line 125, in export_object
    parent_gd_node)
  File "D:\Temp\blender-2.80.0-git.e1d1899e7290-windows64\2.80\scripts\addons\io_scene_godot\converters\mesh.py", line 45, in export_mesh_node
    mesh_id = mesh_exporter.export_mesh(escn_file, export_settings)
  File "D:\Temp\blender-2.80.0-git.e1d1899e7290-windows64\2.80\scripts\addons\io_scene_godot\converters\mesh.py", line 165, in export_mesh
    export_settings,
  File "D:\Temp\blender-2.80.0-git.e1d1899e7290-windows64\2.80\scripts\addons\io_scene_godot\converters\mesh.py", line 219, in make_arrays
    bpy.data.meshes.remove(mesh)
RuntimeError: Error: Mesh 'Cube' is outside of main database and can not be removed from it

Exporting any mesh seems to produce a runtime error. Traced back the error message to this issue, which might be relevant. https://developer.blender.org/T64731#681240

**Minimal reproduction project:**
Open Blender and try to export default scene. Default settings on exporter.

**Comment by Jason0214** [comment] 2019-05-25 21:31
caused by mesh removal API change of Blender2.8, this issue would be fixed with #215

**Comment by Dogpot** [comment] 2019-05-25 21:33
Ah, silly of me to not check if there's already a PR for it, as it's kinda obvious. Thanks!

**Comment by Jason0214** [comment] 2019-05-25 21:43
No worries,  it is always encouraging to open issues once you find
something not working :)

**Comment by Jason0214** [comment] 2019-06-30 19:22
Fixed by #215

**Closed by Jason0214** 2019-06-30 19:22 UTC
Labels: blender2.8, bug
