### ISSUE TITLE
Support exporting shape keys (blend shapes)

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot-blender-exporter#40] opened 2018-06-04 00:35 UTC
* Version : `master` / 88a8803cd

Currently, it seems that the exporter ignores shape keys (or 'blend shapes') when it exports a mesh. But they are quite commonly used for animating facial expressions, or lip syncing(phonemes) in a 3d character, so it'd be good if we could support this feature.

I wish this issue could get priority even though it might look like a minor feature compared to others.

The reason is, we have no viable method of using shape key based facial expressions or lip syncing animations in Godot at this moment, which could be quite a significant limitation since two most widely used open source character models - namely, Manuel Bastioni Lab and Make Human - all support those features through shape keys.

While it is possible to workaround other limitations of Blender exporter by mixing the result from different exporters, like it's the case with materials for example, there's no other exporters that support shape keys reliably with a rigged mesh for now.

There's an issue report for Better Collada (godotengine/collada-exporter#41) which was created in 2016, but apparently that project looks to be made obsolete in favor of Blender exporter or GLTF.

So, I hope this could get resolved before more people begin to use Godot for 3D projects, because facial expressions or phonemes could be quite important features for such type of games.

**Comment by Jason0214** [comment] 2018-06-04 00:40
There is already a PR of supporting shape key, it is already tested and will be merged soon (hopefully tomorrow

**Comment by mysticfall** [comment] 2018-06-04 00:42
Wow, didn't expect to see it happen so fast :) Thanks, and I'll try it as soon as it's merged to the master.

**Comment by sdfgeoff** [comment] 2018-06-04 09:37
As Jason says, see PR #32 
There's an outstanding bug that was spotted today, so it may be another day or two, but sometime very soon it will become supported.

**Comment by sdfgeoff** [comment] 2018-06-07 08:34
PR #32 was merged.

**Comment by mysticfall** [comment] 2018-06-08 12:30
I tested the new version with my model (https://github.com/mysticfall/AlleyCat/blob/master/Design/Blender/Characters/Human/Female/Body.blend) and it successfully exported an `.escn` file with a reasonable file size in a few minutes.

But none of the exported shape keys seem to work if I change them inside Godot. Is there additional steps to make them work inside the editor?

**Comment by Jason0214** [comment] 2018-06-09 07:15
It is reasonable to take a few minutes, as for each shape key it is like exporting the mesh again. (Actually I can not even finish exporting the Body.blend, there are dozens of shape keys in the mesh! and blender only takes up one CPU and no GPU acceleration)

For simplicity I only keeps one shape key in Body.blend remove others and test it.  I found the exported mesh is deformed if shape key is exported.  And when I **remove the subdivision modifier from the mesh**, the exported mesh and shape key works perfectly, so I suppose mostly like the problem is caused by **subdivision modifier**. I will keep thinking about why this happens and come about a solution to it.

**Comment by mysticfall** [comment] 2018-06-09 08:03
@Jason0214 When I said it took several minutes, I actually mentioned it in a sense that it's a vast improvement over how it was with Better Collada which just freezes my whole desktop (even with 'Apply Modifier' unchecked) as I commented in a relevant issue :)

By the way, I should have said that I tested with _Apply Modifiers_ option unchecked. When I export the model and move the sliders under `blend_shapes` section on the imported mesh node, I don't see any differences in the viewport.

**Comment by Jason0214** [comment] 2018-06-09 08:41
I tested one shape key (the_closed_eye_max one) it works fine by moving the slider in blend_shapes, could you tell me which blend_shape doesn't work? then, I will go to test it

**Comment by mysticfall** [comment] 2018-06-09 08:52
I tested again with removing everything except for `basis` and `Expressions_eyeClosedL_max` but it didn't work either.

Could it be the case that it was because I'm using a different version of Godot/Blender? I tested it with the master branch (`2ff31bada` revision) of Godot, and Blender 2.79. And I exported my model with the skeleton (which looks deformed, but not the mesh) and without animations.

**Comment by Jason0214** [comment] 2018-06-09 19:06
confirmed when  **Apply Modifier** is **NOT** used, the exported `blend_shape` doesn't work. It is a bug.

but when **Apply Modifier** is used and remove the **subdivision modifier**, the `blend_shapes` does being exported and work correctly

**Comment by sdfgeoff** [comment] 2018-06-15 07:56
There is now a check against the modifiers in blender that will warn the user in the case they try to export a mesh with shapekeys and modifiers.

There are technical reasons why exporting shapekeys with modifiers that generate topology (eg bevel, subsurf) is, at the very least, rather difficult.

**Closed by sdfgeoff** 2018-06-15 07:56 UTC
