### ISSUE TITLE
Export replaces objects with duplicates of others

### ISSUE THREAD

**Issue by GWRon** [godotengine/godot-blender-exporter#113] opened 2018-11-12 11:57 UTC
Using latest revision https://github.com/godotengine/godot-blender-exporter/commit/ba02eb0a17f38ecd2dcc9bae1bcccf0f94d2006d (and happened before too):

This is the blender layout:
![blender](http://i.imgur.com/PPZ4Pnd.png)

- white block is there to see if shadows work as the light seemed to ignore the windows in the wall or the wall at all (maybe an issue with lightmap baking and GI probes which I tried too)
- other layers in the .blend file below contain other "roof/wall"-objects which had very similar issues

This is when I import it into Godot:
![godot](http://i.imgur.com/g8Ne2sB.png)

- objects get displaced
- some objects have the mesh of other objects:
- - white cube becomes the wall
- - orange object becomes the ground+wall object

Sometimes the import works - I have to move some objects before exporting, export to a ESCN file again, directly open that file in Godot, then with some luck it shows the correct export - from then on the TSCN-file using the ESCN instance is updated to the correct state too - I think this is a Godot issue, not one of this addon.

In other tries the export lead to a duplicate pair of boots (the "roof" got replaced by another pair of boots). Interesting side note: the boots next to the bed lost their material settings (became pure white) while the boots "formerly known as roof" received the materials set in Blender (maybe this helps narrowing down the issue).

Exporting via "DAE" (Collada) keeps objects intact but of course needs more adjustments (material, light, ...)

I exported way more complex sceneries via the addon and did not encounter these problems here so I am a bit clueless what could be the source of the issue.

Here is the Godot-Project-folder including the "assets.raw" folder containing the .blend file. Make sure to only export the active layer/objects there - other layers contain other wall setups (I thought it might have run into trouble because of intersecting polygons or not-closed/non-manifold objects).

[DontBotherSanta.zip](https://github.com/godotengine/godot-blender-exporter/files/2571799/DontBotherSanta.zip)

**Comment by GWRon** [comment] 2018-11-12 12:05
Just tried to export it again - this time I applied the rotation of the left wall (ctrl + a -> "rotation") and saved again. For now it _seem_ to have worked:

![exported](http://i.imgur.com/m0zT6sj.png)

Pressing play leads to this:
![img](http://i.imgur.com/iMbsev2.png)
As you see we got another pair of boots - and the wall is not rendered (only the white cube is having a shadow). Dunno if that is an "import" issue of Godot - or an "export" issue which somehow mangles Godot.

**Comment by sdfgeoff** [comment] 2018-11-12 12:51
I don't know what version of Godot you are using, but up until fairly recently, re-importing a file with it open caused huge issues - either corrupting meshes, switching which mesh an object showed, moving them, all other odds and ends. If the scene happens to preloaded in a singleton you are completely sunk as then the file is always open and you can never re-import it..... The only way to recover from this was to re-import the file with the file closed.
If you are using an official stable release, this is likely to the the problem. 

Try doing a clean import (close godot, delete the .import folder, open godot).

On the other hand, the wall rotation issue may not be a godot issue. This may be something incorrect in the conversion from z-up to y-up space. By chance does the wall have a collision shape?

I'm fascinated by the flying boots. I have zero idea what could be causing that from the exporter side.

**Comment by Zireael07** [comment] 2018-11-12 13:36
Cycles materials are not exportable.

**Comment by sdfgeoff** [comment] 2018-11-12 14:29
@Zireal: JasonLu recently added primitive cycles materials support.

> yet it lacks a proper solution for a "nice flow" in the production pipeline.

Exactly the issue I'm facing at work. You don't have to close godot completely. You only have to close any scenes containing the model. It's still a bit of a pain, but the other developers got used to it after a while.
It may have been solved in this PR https://github.com/godotengine/godot/issues/22673
Also see this issue report: https://github.com/godotengine/godot/issues/19966

**Comment by GWRon** [comment] 2018-11-12 15:36
The PR you linked seem to have issues with cyclic dependency (a uses b, b uses a). Segfaults might happen if one somehow thinks the other item is already instantiated. Cannot imagine that it somehow is connected to this issue. It could only happen if I use linked duplicates and some kind of "IK animation" which tries to get solved before the duplicate is instanciated (which wants to solve the IK then too) - sorry if that example does not suit that well.
Nonetheless I do not see where concurrent instantiation of cyclid dependencies is happening here.

The issue report https://github.com/godotengine/godot/issues/19966 is indeed something I experienced too - reloading without apparent changes in the editor views. But I also exported to .escn without Godot showing the "reloading" screen, as if it wasn't aware of the change. Dunno how many elements of the filemtime Godot uses (hours, minutes ... seconds?) so if you are quick on exporting it might ignore the change ("h:m" of .import is the same as the "h:m" of the ".escn" file).

Aside of that - thanks for trying to help.

**Comment by Jason0214** [comment] 2018-11-12 19:54
@GWRon I think the mesh out of order is caused by you updating an opened scene file (i.e. you are write to the .escn file when it's opened). I tried to clear the .import files in your zipped scene, then open the .escn again, the object transform and meshes would be in the right position. 
As sdfgeoff pointed out, it would cause some weird behaviour even seg fault if write to an opened scene file, It is kind of a pain of the workflow for now. 

----
And the Wall material missing issue,  it didn't happen on my platform godot (I am on OSX and I have tried Godot 3.0.5 and a custom build of 3.1 ), both got correct scene, material and shadow.  I find the Wall.material in your zipped scene has a very small size, so it could be the material didn't correctly imported from .escn in your Godot, might be a Godot issue.  Anyway I will try Godot.3.0.6 and beta later and update here.

**Comment by GWRon** [comment] 2018-11-12 20:05
@Jason0214 
Thanks for the elaborative answer.

If the opened file + linked asset modification is problematic, then it would happen to all externally modified asset files - .dae, .obj ... all files which are linked instead of getting "one time"-transformed into a godot-internal structure.


@ material
I used latest stable (3.0.6) and latest beta (as I wanted to use the hinted-typing to avoid some issues I have with GDScript and its "freedom to code" :-)).

**Comment by Jason0214** [comment] 2018-11-12 21:52
I observed some error throwing when importing the escn on Godot 3.0.6, though the scene is imported correctly, not sure if it is the reason the material failed to import on your platform
<img width="1061" alt="screen shot 2018-11-12 at 13 16 27" src="https://user-images.githubusercontent.com/19422835/48377077-9e8cd700-e681-11e8-82bf-af19c76f79c9.png"> 

I double checked the shader code has the correct format, it seems like a godot issue to me in tokenize the shader.

**Comment by GWRon** [comment] 2018-11-12 22:17
Yes, saw these errors too - and assumed some shader issue.
That "it's dead"-icon of the .escn file might indicate the error (did only see it there).

For "simple" materials shaders might be overkill (less easy to adjust from within Godot). So if there is only a basic material consisting of albedo + roughness, then this could be done with the classic "SpatialMaterial" thing (at least for now this is easier to adjust).


@ failed to import
So why was it failing once - but after I removed the second material in Blender (and undo'd it then) the exported file worked in Godot (means it casted shadows properly). If it failed again then it should lead to the above described shadow issue.

Yet it seems this issue at least exposed a flaw with Godot and the shader code.

**Comment by Jason0214** [comment] 2018-11-13 17:01
Ah, sorry I didn’t follow you completely, didn’t notice the succeed you mentioned. Would you willing to try to open your escn in a clean godot project again and put the log here? it would be the helpful to decide the issue is in blender exporting or escn imported to godot.

**Comment by GWRon** [comment] 2018-11-13 17:07
Will do later this evening. Please be a bit patient.

**Comment by GWRon** [comment] 2018-11-13 19:22
Uhmm... where to find the .log file? For now I only see this Error-tab in the editor which I can only partially select (seems the UI interaction is incomplete...)

This happens when I created a new application, added a new folder "models" from within Thunar/File Explorer. I then saved the .escn file from Blender right into this "models" folder. It updated materials in Godot and I double clicked on the .escn file and selected to create a new instance.

```
Godot Engine v3.1.alpha.official (c) 2007-2018 Juan Linietsky, Ariel Manzur & Godot Contributors.
0 
 :1 - Expected 'shader_type' at the beginning of shader.
 drivers/gles3/rasterizer_storage_gles3.cpp:1935 - Condition ' err != OK ' is true.
0 
 :1 - Expected 'shader_type' at the beginning of shader.
 drivers/gles3/rasterizer_storage_gles3.cpp:1935 - Condition ' err != OK ' is true.
0 
 :1 - Expected 'shader_type' at the beginning of shader.
 drivers/gles3/rasterizer_storage_gles3.cpp:1935 - Condition ' err != OK ' is true.
0 
 :1 - Expected 'shader_type' at the beginning of shader.
 drivers/gles3/rasterizer_storage_gles3.cpp:1935 - Condition ' err != OK ' is true.
0 
 :1 - Expected 'shader_type' at the beginning of shader.
 drivers/gles3/rasterizer_storage_gles3.cpp:1935 - Condition ' err != OK ' is true.
0 
 :1 - Expected 'shader_type' at the beginning of shader.
 drivers/gles3/rasterizer_storage_gles3.cpp:1935 - Condition ' err != OK ' is true.
0 
 :1 - Expected 'shader_type' at the beginning of shader.
 drivers/gles3/rasterizer_storage_gles3.cpp:1935 - Condition ' err != OK ' is true.
0 
 :1 - Expected 'shader_type' at the beginning of shader.
 drivers/gles3/rasterizer_storage_gles3.cpp:1935 - Condition ' err != OK ' is true.
0 
 :1 - Expected 'shader_type' at the beginning of shader.
 drivers/gles3/rasterizer_storage_gles3.cpp:1935 - Condition ' err != OK ' is true.
0 
 :1 - Expected 'shader_type' at the beginning of shader.
 drivers/gles3/rasterizer_storage_gles3.cpp:1935 - Condition ' err != OK ' is true.
0 
 :1 - Expected 'shader_type' at the beginning of shader.
 drivers/gles3/rasterizer_storage_gles3.cpp:1935 - Condition ' err != OK ' is true.
0 
 :1 - Expected 'shader_type' at the beginning of shader.
 drivers/gles3/rasterizer_storage_gles3.cpp:1935 - Condition ' err != OK ' is true.
0 
 :1 - Expected 'shader_type' at the beginning of shader.
 drivers/gles3/rasterizer_storage_gles3.cpp:1935 - Condition ' err != OK ' is true.
0 
 :1 - Expected 'shader_type' at the beginning of shader.
 drivers/gles3/rasterizer_storage_gles3.cpp:1935 - Condition ' err != OK ' is true.
0 
 :1 - Expected 'shader_type' at the beginning of shader.
 drivers/gles3/rasterizer_storage_gles3.cpp:1935 - Condition ' err != OK ' is true.
0 
 :1 - Expected 'shader_type' at the beginning of shader.
 drivers/gles3/rasterizer_storage_gles3.cpp:1935 - Condition ' err != OK ' is true.
0 
 :1 - Expected 'shader_type' at the beginning of shader.
 drivers/gles3/rasterizer_storage_gles3.cpp:1935 - Condition ' err != OK ' is true.
0 
 :1 - Expected 'shader_type' at the beginning of shader.
 drivers/gles3/rasterizer_storage_gles3.cpp:1935 - Condition ' err != OK ' is true.
0 
[...]
```

**Comment by Jason0214** [comment] 2018-11-14 02:49
Yeah, I am talking about the log in the editor tab. hmm nothing interest,  anyway, I will open an issue in godot about this 'shader_type' thing, let's see if it is the reason cause your material not successfully imported

**Comment by Jason0214** [comment] 2018-12-06 04:14
@GWRon I found the external material (.material file) may overwrite each other if they have same name, so I removed it in the current HEAD, you can give it a try if you want to see if your problem still exists. I will close this issue for now, but feel free to reopen it if you have further questions or issues.

**Closed by Jason0214** 2018-12-06 04:14 UTC
